### ISSUE TITLE
eros mock 报错

### ISSUE THREAD

**Issue by shawn-tangsc** [bmfe/eros-cli#9]
```
tangsicheng:home-app-eros(master *+)$eros mock
**日志**：server 运行成功, 端口为 3888
**日志**：按 Ctrl + C 结束进程
/usr/local/lib/node_modules/eros-cli/node_modules/orchestrator/index.js:153
                        throw err;
                        ^

Error: task "mock" is not defined
    at Gulp.sequence (/usr/local/lib/node_modules/eros-cli/node_modules/sequencify/index.js:14:9)
    at Gulp.Orchestrator.start (/usr/local/lib/node_modules/eros-cli/node_modules/orchestrator/index.js:115:9)
    at Server.<anonymous> (/usr/local/lib/node_modules/eros-cli/lib/commands/mock.js:65:14)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1288:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)

```

**Comment by PerseveranceZ** [comment]
@shawn-tangsc fixed in eros-cli V2.0.5。
